### PR TITLE
added version 58 for ubuntu 16.04

### PR DESCRIPTION
**Pull request by dubvulture**
I hope I didn't miss anything

### CODE REVIEW

**Comment by Eloston** [comment]
Looks good :+1:

Did you need to do anything special to build 16.04 binaries, or did it work out-of-the-box?

**Comment by dubvulture** [comment]
Just a problem related to *dpkg-checkbuilddeps* which didn't accept my version of libcups2 (2.1.3-4ubuntu0.2) so I had to force the required version's installation with

    sudo apt install libcups2=2.1.3-4 libcups2-dev=2.1.3-4

**Comment by Eloston** [comment]
Really? That's strange. The control file requires only `libcups2-dev (>= 1.5.0)`. I'm not sure why it's rejecting anything in version 2.x.x. Do you have the exact error message?

**Comment by dubvulture** [comment]
Nope, lost in the terminal after compiling.
It was this version, but upon further inspections it seems it has been removed 2 months ago.
https://launchpad.net/ubuntu/xenial/amd64/libcups2-dev/2.1.3-4ubuntu0.2
For some reasons updating my system (even several times after the publish date) didn't upgrade this package.

So yeah, might not be a problem.

**Comment by Eloston** [comment]
Alright. If you run into the problem again, you can create a new issue on the main repository.

Thanks for contributing binaries!

**Pull request merged**
