### PR TITLE
add binaries for portable linux build of 126.0.6478.182-1

### PR DESCRIPTION
**Pull request by clickot**

### CODE REVIEW

**Comment by clickot** [comment]
as far as i can see site generation fails because of missing version class in package pkg_resources and has nothing to do with my config files, so I don't know how to fix this. Afaik these classes have been removed in newer versions of the pkg_resoures package

**Comment by PF4Public** [comment]
Would it be safe to merge your PR, could we break something then?

**Comment by clickot** [comment]
I fixed the problem by replacing usage of 'version' class from deprecated 'pkg_resources' package with version class from newer 'packaging' package.

**Comment by PF4Public** [comment]
Looks good now, ~oder~ isn't it?

**Review by PF4Public — APPROVED** [review]

**Pull request merged**
