### PR TITLE
Add AppImage v69.0.3497.100-2

### PR DESCRIPTION
**Pull request by intika**

### CODE REVIEW

**Comment by Eloston** [comment]
Would you be able to submit a PR to ungoogled-chromium for the scripts you used to generate the AppImage?

**Comment by intika** [comment]
Yes i will do that :+1:

**Comment by intika** [comment]
just asked you the question in here https://github.com/Eloston/ungoogled-chromium/issues/36#issuecomment-427609114

**Comment by intika** [comment]
should i add the whole script https://github.com/AppImage/AppImages or just some lines that git clone the project ?

**Comment by intika** [comment]
Ok... as the script need some adjustment to work with non debian build i think i will just integrate the whole script i used to avoid update that would break it

**Comment by intika** [comment]
Okay i know what to do to make every one happy :D i am PR ing appimage for rhel based system and i will just use git clone on the script that i am writing for a pr to ug

**Comment by intika** [comment]
Done, just testing on build server before pr

**Comment by intika** [comment]
Just added an update for my links i did uploaded all my builds to opendesktop.org... i updated just to avoid dead links on old builds

**Pull request merged**
