### PR TITLE
Add 87.0.4280.141-1.unportable1 for Debian/Ubuntu (unportable)

### PR DESCRIPTION
**Pull request by SugaryHull**

### CODE REVIEW

**Review by Eloston — APPROVED** [review]
Thanks :+1:

**Comment by SugaryHull** [comment]
@Eloston It seems I forgot to add the "_amd64" somewhere (either my upload or my pull-request), so they have been erroneously listed as i686 packages on the binaries page. What would it take to correct that?

**Comment by SugaryHull** [comment]
It turns out my .INI file was supposed to be placed in the "amd64" subdirectory of "config/unportable_debian". Would that be something I could fix with a new pull-request?

**Comment by Eloston** [comment]
Oh yeah, I didn't catch that. Yes, you can fix that with a new PR. Any changes to the config will be reflected in the resulting HTML.

**Comment by SugaryHull** [comment]
@Eloston My new pull-request can be found [here](https://github.com/ungoogled-software/ungoogled-chromium-binaries/pull/228).

**Pull request merged**
