### PR TITLE
add 72.0.3626.122-1 macOS binary as dev

### PR DESCRIPTION
**Pull request by kramred**

### CODE REVIEW

**Comment by kramred** [comment]
didn't see the other pull req. for the macOS binary - you can close this pull req. or pick either

**Comment by Eloston** [comment]
Just curious, does your binary differ from the other?

**Comment by kramred** [comment]
Yes the hashes of the dmg differ. Will download the other an check further

**Comment by Eloston** [comment]
That's fine, there's probably no cause for concern. I was just curious to see if the entire package binary is reproducible. Let me know if you find anything out, though.

**Comment by kramred** [comment]
These binary files differ:

* Chromium Framework (155 MB; 1.4 MB bsdiff – see below)
* crashpad_handler (1.7 MB; 395 Byte bsdiff)
* SaveAccessoryView.nib (8.6 KB; 998 Byte bsdiff)
* TaskManager.nib (13 KB; 948 Byte bsdiff)
* AlertNotificationService (1.4 MB; 403 Byte bsdiff)

`bsdiff` creates a 1.4 MB binary patch file for the two `Chromium Framework` files (1.4 MB bzip2, 1.4 MB xz) [bsdiff homepage](http://www.daemonology.net/bsdiff/)

`courgette` (which is funnily part of the [Chromium package](https://chromium.googlesource.com/chromium/src/courgette/)) generates a 3.8 MB patch file for the two `Chromium Framework` files (1.5 MB bzip2, 1.3 MB xz)

the Info.plist files differ in the `BuildMachineOSBuild` key
```xml
<key>BuildMachineOSBuild</key>
<string>18D109</string>
```

vs.
```xml
<key>BuildMachineOSBuild</key>
<string>17G5019</string>
```

Output from `diff` commands:

```bash
diff -qr Chromium_kramred.app/ Chromium_chase9.app/
```

```diff
Files Chromium_kramred.app/Contents/Info.plist and Chromium_chase9.app/Contents/Info.plist differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Chromium Framework and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Chromium Framework differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Helpers/crashpad_handler and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Helpers/crashpad_handler differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Resources/Info.plist and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Resources/Info.plist differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Resources/SaveAccessoryView.nib and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Resources/SaveAccessoryView.nib differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Resources/TaskManager.nib and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Resources/TaskManager.nib differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Resources/app_mode_loader.app/Contents/Info.plist and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Resources/app_mode_loader.app/Contents/Info.plist differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Chromium Framework and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Chromium Framework differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Helpers/crashpad_handler and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Helpers/crashpad_handler differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/Info.plist and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/Info.plist differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/SaveAccessoryView.nib and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/SaveAccessoryView.nib differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/TaskManager.nib and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/TaskManager.nib differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/app_mode_loader.app/Contents/Info.plist and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/app_mode_loader.app/Contents/Info.plist differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/XPCServices/AlertNotificationService.xpc/Contents/Info.plist and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/XPCServices/AlertNotificationService.xpc/Contents/Info.plist differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/XPCServices/AlertNotificationService.xpc/Contents/MacOS/AlertNotificationService and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/XPCServices/AlertNotificationService.xpc/Contents/MacOS/AlertNotificationService differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/Current/Chromium Framework and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/Current/Chromium Framework differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/Current/Helpers/crashpad_handler and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/Current/Helpers/crashpad_handler differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/Current/Resources/Info.plist and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/Current/Resources/Info.plist differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/Current/Resources/SaveAccessoryView.nib and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/Current/Resources/SaveAccessoryView.nib differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/Current/Resources/TaskManager.nib and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/Current/Resources/TaskManager.nib differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/Current/Resources/app_mode_loader.app/Contents/Info.plist and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/Current/Resources/app_mode_loader.app/Contents/Info.plist differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/Current/XPCServices/AlertNotificationService.xpc/Contents/Info.plist and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/Current/XPCServices/AlertNotificationService.xpc/Contents/Info.plist differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/Current/XPCServices/AlertNotificationService.xpc/Contents/MacOS/AlertNotificationService and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/Current/XPCServices/AlertNotificationService.xpc/Contents/MacOS/AlertNotificationService differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/XPCServices/AlertNotificationService.xpc/Contents/Info.plist and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/XPCServices/AlertNotificationService.xpc/Contents/Info.plist differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/XPCServices/AlertNotificationService.xpc/Contents/MacOS/AlertNotificationService and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/XPCServices/AlertNotificationService.xpc/Contents/MacOS/AlertNotificationService differ
Files Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Helper.app/Contents/Info.plist and Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Helper.app/Contents/Info.plist differ
```

```bash
git diff -U0 --no-index Chromium_kramred.app/ Chromium_chase9.app/
diff --git a/Chromium_kramred.app/Contents/Info.plist b/Chromium_chase9.app/Contents/Info.plist
```

```diff
index 974e02f..dab71e2 100644
--- a/Chromium_kramred.app/Contents/Info.plist
+++ b/Chromium_chase9.app/Contents/Info.plist
@@ -6 +6 @@
-       <string>17G5019</string>
+       <string>18D109</string>
diff --git a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Chromium Framework b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Chromium Framework
index b31accf..8a6366c 100755
Binary files a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Chromium Framework and b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Chromium Framework differ
diff --git a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Helpers/crashpad_handler b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Helpers/crashpad_handler
index cbf6fee..5d059c6 100755
Binary files a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Helpers/crashpad_handler and b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Helpers/crashpad_handler differ
diff --git a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/Info.plist b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/Info.plist
index adfb72d..40af7b3 100644
--- a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/Info.plist 
+++ b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/Info.plist  
@@ -6 +6 @@
-       <string>17G5019</string>
+       <string>18D109</string>
diff --git a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/SaveAccessoryView.nib b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/SaveAccessoryView.nib
index b754e9d..b8a2c3a 100644
Binary files a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/SaveAccessoryView.nib and b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/SaveAccessoryView.nib differ
diff --git a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/TaskManager.nib b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/TaskManager.nib
index ff7ba86..081dc76 100644
Binary files a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/TaskManager.nib and b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/TaskManager.nib differ
diff --git a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/app_mode_loader.app/Contents/Info.plist b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/app_mode_loader.app/Contents/Info.plist
index 1bc492e..4b514f0 100644
--- a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/app_mode_loader.app/Contents/Info.plist    
+++ b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/Resources/app_mode_loader.app/Contents/Info.plist     
@@ -6 +6 @@
-       <string>17G5019</string>
+       <string>18D109</string>
diff --git a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/XPCServices/AlertNotificationService.xpc/Contents/Info.plist b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/XPCServices/AlertNotificationService.xpc/Contents/Info.plist
index c85901c..2a76577 100644
--- a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/XPCServices/AlertNotificationService.xpc/Contents/Info.plist 
+++ b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/XPCServices/AlertNotificationService.xpc/Contents/Info.plist
  
@@ -6 +6 @@
-       <string>17G5019</string>
+       <string>18D109</string>
diff --git a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/XPCServices/AlertNotificationService.xpc/Contents/MacOS/AlertNotificationService b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/XPCServices/AlertNotificationService.xpc/Contents/MacOS/AlertNotificationService
index 7fa52e0..71637c5 100755
Binary files a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/XPCServices/AlertNotificationService.xpc/Contents/MacOS/AlertNotificationService and b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Framework.framework/Versions/A/XPCServices/AlertNotificationService.xpc/Contents/MacOS/AlertNotificationService differ
diff --git a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Helper.app/Contents/Info.plist b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Helper.app/Contents/Info.plist
index 48754e8..94702ff 100644
--- a/Chromium_kramred.app/Contents/Versions/72.0.3626.122/Chromium Helper.app/Contents/Info.plist      
+++ b/Chromium_chase9.app/Contents/Versions/72.0.3626.122/Chromium Helper.app/Contents/Info.plist       
@@ -6 +6 @@
-       <string>17G5019</string>
+       <string>18D109</string>
```

**Pull request closed without merging**
