### PR TITLE
Add 78.0.3904.70-1 binaries for Arch Linux

### PR DESCRIPTION
**Pull request by jstkdng**
I also had to edit the file utilities/platform_ini_generator.py to get it to work, probably because of arch, should I add that too?

### CODE REVIEW

**Comment by Eloston** [comment]
I'm not going to merge this until ungoogled-chromium-archlinux is updated, and definitely not until ungoogled-chromium is tagged with this version (https://github.com/Eloston/ungoogled-chromium/pull/840). Merging a binary without the corresponding code is confusing to the user, at the very least.

Also, what change did you have to make to `platform_ini_generator.py`?

**Comment by jstkdng** [comment]
my bad, it was the ```site_generator.py``` file.
Probably because of some arch package, does that script work for debian?
```patch
diff --git a/utilities/site_generator.py b/utilities/site_generator.py
index 39a4168..cf0f6b0 100644
--- a/utilities/site_generator.py
+++ b/utilities/site_generator.py
@@ -19,7 +19,7 @@ import string
 import sys
 
 import markdown # Python-Markdown: https://github.com/waylan/Python-Markdown
-from pkg_resources.extern.packaging.version import LegacyVersion as VersionSortKey
+from packaging.version import LegacyVersion as VersionSortKey
 
 if __name__ == "__main__" and (__package__ is None or __package__ == ""):
     def _fix_relative_import():
```

**Comment by Eloston** [comment]
`pkg_resources` is part of `setuptools` (which is the name of the PyPI package), but `pkg_resources` is packaged as `python3-pkg-resources` on Debian. I don't have `packaging` on my system, who provides that?

**Comment by jstkdng** [comment]
Arch has pkg_resources included in ```python-setuptools```, and packaging is included in ```python-packaging```.
A better patch would be then:
```patch
diff --git a/utilities/site_generator.py b/utilities/site_generator.py
index 39a4168..d95e4c2 100644
--- a/utilities/site_generator.py
+++ b/utilities/site_generator.py
@@ -19,7 +19,10 @@ import string
 import sys
 
 import markdown # Python-Markdown: https://github.com/waylan/Python-Markdown
-from pkg_resources.extern.packaging.version import LegacyVersion as VersionSortKey
+try:
+    from pkg_resources.extern.packaging.version import LegacyVersion as VersionSortKey
+except ImportError:
+    from packaging.version import LegacyVersion as VersionSortKey
 
 if __name__ == "__main__" and (__package__ is None or __package__ == ""):
     def _fix_relative_import():
```

**Comment by Eloston** [comment]
With 0c0235ff231c5a321a97462d72ef0e3de99aa176, I've added a basic `requirements.txt` file. Per the updated README instructions, you should just need to run `python3 -m pip install utilities/requirements.txt` and the script *should* work.

**Comment by jstkdng** [comment]
Nice, but since a new version that fixed a vulnerabilty has been released, I'll pr that one.

**Pull request closed without merging**
