### PR TITLE
Add 83.0.4103.97-1.1 for AppImage and Linux Portable

### PR DESCRIPTION
**Pull request by MikeModder**

### CODE REVIEW

**Comment by MikeModder** [comment]
Nice catch, should have hit tab one more time!

**Comment by TT1** [comment]
I was very much looking forward to the Ungoogled-Chromium AppImage update. Thanks much for making it. Unfortunately, it won't run with MX-18.3. The message I get when launching it from a terminal is, in part:

/lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.27' not found (required by /tmp/.mount_ungoog0BnduA/opt/google/chrome/chrome)

Is there any way this could be resolved? Is the library not a part of the AppImage?

**Comment by MikeModder** [comment]
I did my initial tests on Void Linux (and a friend on Ubuntu 20.04) and had no issues. I just pulled out a Ubuntu 18.04 machine and am getting a similar error.

```
/tmp/.mount_ungoogk3hTws/opt/google/chrome/chrome: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.mount_ungoogk3hTws/opt/google/chrome/chrome)
```

The machine I built it on was running Debian 10, so I guess it built against that version of glibc (2.28). I can redo the builds no problem, I'm just not sure how to change the version of glibc used.

**Comment by TT1** [comment]
Thanks, Mike. MX Linus-18.3 is running Debian 9 Jessie with glib 2.24. 
Would be great if UC-AppImage could work with that since Jessie is still 
ESR until 2022. UC-71 works great but I've been concered about its 
age/safety. There have been requests on the forum for a more recent version.

Thanks again.

Wayne

**Pull request merged**
