### PR TITLE
add 118.0.5993.70-1 binaries for portable linux

### PR DESCRIPTION
**Pull request by clickot**

### CODE REVIEW

**Comment by clickot** [comment]
@networkException, @Nifury,  could some of you be so kind to approve this PR befor .88 is ready?

**Comment by Nifury** [comment]
I don’t have permission unfortunately 😂

**Comment by clickot** [comment]
> I don’t have permission unfortunately 😂

makes sense since i can approve yours :-D

**Review by networkException — APPROVED** [review]

**Comment by networkException** [comment]
sorry mb, need to catch up with ~550 emails still 🫠

**Comment by clickot** [comment]
@networkException didn't want to stress, thank you very much!

**Pull request merged**
