### PR TITLE
Add 93.0.4577.82-1 for Manjaro

### PR DESCRIPTION
**Pull request by zocker-160**
Build using the latest Manjaro stable update from 2021-08-17.

### CODE REVIEW

**Comment by zocker-160** [comment]
Updated to 93.0.4577.82-1
Build using the latest Manjaro stable update from 2021-09-16.

**Comment by zocker-160** [comment]
Updated to 94.0.4606.54-1
Build using the latest Manjaro stable update from 2021-09-24.

Will this ever going to get merged?

**Comment by zocker-160** [comment]
Updated to 94.0.4606.61-1
Build using the latest Manjaro stable update from 2021-09-24.

Will this ever going to get merged?

**Comment by Eloston** [comment]
Yes, my apologies. I overlooked this. LGTM :+1: 

I will be adding some mechanisms to ensure people see this.

**Pull request merged**
