### PR TITLE
Add 112.0.5615.138-1 binaries for portable linux

### PR DESCRIPTION
**Pull request by clickot**

### CODE REVIEW

**Comment by clickot** [comment]
with 112.0.5615.165, this PR is obsolete

**Comment by networkException** [comment]
yea and this is a windows only release

**Comment by clickot** [comment]
i learned i should check which releases are "linux-relevant". about 8h build time for nothing.... :-)

**Comment by networkException** [comment]
if that helps you can also get pinged by the update issues (like https://github.com/ungoogled-software/ungoogled-chromium/issues/2320)

**Comment by clickot** [comment]
hello @networkException , thanks for the hint. what would i have to do to get pinged by such issues? since some github action creates them, i suppose? btw: i created a pull request for the 165-1 version.

**Comment by PF4Public** [comment]
@clickot See https://github.com/ungoogled-software/ungoogled-chromium/pull/2326

**Pull request closed without merging**
