### PR TITLE
Add Appimage & Portable v70.0.3538.110-1

### PR DESCRIPTION
**Pull request by intika**

### CODE REVIEW

**Comment by Eloston** [comment]
You can pass the script as an argument to the interpreter if you need to.

Would it help to have a script to run a local server?

**Comment by intika** [comment]
I just reverted the change... 
do you want me to close this PR rebase and start over or is it ok like that ?

**Comment by intika** [comment]
wait i'll do it properly ;)

**Comment by Eloston** [comment]
> Its okay don't waste your time changing the script its perfect as it is :)

It wouldn't modify the script. It'll be a new small script using `http.server` so you can view the HTML files without needing to push to GitHub.

> wait i'll do it properly ;)

For future reference, it's not necessary to do this. I can squash your changes into one commit and merge it via the GitHub UI. Keeps things clean even if people make mistakes along the way :)

**Comment by intika** [comment]
gotcha :) it's been a while i did not use the UI they did a good job tho... 
yeah i gotcha for the script as you like if you want to add it but it's not a must :)

**Pull request closed without merging**
