### PR TITLE
Add 90.0.4430.85-1.1 binaries for Portable Linux 64-bit

### PR DESCRIPTION
**Pull request by Joffreybvn**

### CODE REVIEW

**Comment by mdedonno1337** [comment]
Hi,
Juste to be sure, this is the output of the "./build.sh", "./package.sh" scripts, file used as input for the "./package.appimage.sh.ungoogin" script, am'I understand correctly ?
Thanks

**Comment by Joffreybvn** [comment]
Hello,
Yes I build it with the `./docker-build.sh` from one of your previous commit [3044f89d5623565f8d6c605dc62edf891eec7448](https://github.com/mdedonno1337/ungoogled-chromium-portablelinux/tree/3044f89d5623565f8d6c605dc62edf891eec7448)

**Comment by mdedonno1337** [comment]
Haa great, I did not know that the archive was usable as-is.
Thanks for the information!

**Review by Eloston — APPROVED** [review]
:+1:

**Pull request merged**
