### PR TITLE
Add signed macOS builds of 122.0.6261.111-1.1

### PR DESCRIPTION
**Pull request by claudiodekker**
This PR was [automatically triggered](https://github.com/claudiodekker/ungoogled-chromium-binaries/actions/runs/8213421557) by the release of [code-signed build 122.0.6261.111-1.1](https://github.com/claudiodekker/ungoogled-chromium-macos/releases/tag/122.0.6261.111-1.1) of ungoogled-chromium for macOS, which itself is based on [this ungoogled-software/ungoogled-chromium-macos build](https://github.com/ungoogled-software/ungoogled-chromium-macos/releases/tag/122.0.6261.111-1.1).

### CODE REVIEW

**Comment by PF4Public** [comment]
@networkException @clickot Should we insist on correctly filled `github_author` field?

**Comment by networkException** [comment]
I'd be in favor of that

**Comment by claudiodekker** [comment]
Adjusted the author for future auto-generations - Will update this PR & the PR created a few minutes ago.

**Comment by claudiodekker** [comment]
@PF4Public All done!

**Comment by networkException** [comment]
Closed in favor of #519

**Pull request closed without merging**
