### PR TITLE
Add 123.0.6312.86-1 for Windows

### PR DESCRIPTION
**Pull request by Nifury**

### CODE REVIEW

**Comment by clickot** [comment]
site generation fails because of the "time zone" part in publication_time:
`publication_time = 2024-03-29T16:06:05.535674**+00:00**`
could you please remove the `+00:00` part?
see also my commit https://github.com/ungoogled-software/ungoogled-chromium-binaries/pull/517/commits/facf2e7f18fd852e8b56f9e000da8eae32f0491c

**Comment by Nifury** [comment]
Ouch I didn't know that timezone was part of the iso format. 
Thanks for pointing that out and fixing my previous commits!

**Comment by clickot** [comment]
there still seems to be a file (123.0.6312.58-1.ini) with timezone data:

```
Parsing version ini: config/platforms/windows/64bit/123.0.6312.58-1.ini
               ^^^^^^^^^^^^^
  File "/home/runner/work/ungoogled-chromium-binaries/ungoogled-chromium-binaries/utilities/site_generator.py", line 180, in read_config
    root_dir.recursively_read_children()
  File "/home/runner/work/ungoogled-chromium-binaries/ungoogled-chromium-binaries/utilities/site_generator.py", line 160, in recursively_read_children
    tmp_dir.recursively_read_children()
  File "/home/runner/work/ungoogled-chromium-binaries/ungoogled-chromium-binaries/utilities/site_generator.py", line 159, in recursively_read_children
    tmp_dir = PlatformDirectory(entry, self)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/ungoogled-chromium-binaries/ungoogled-chromium-binaries/utilities/site_generator.py", line 150, in __init__
    new_version = PlatformVersion(config_path, self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/ungoogled-chromium-binaries/ungoogled-chromium-binaries/utilities/site_generator.py", line 105, in __init__
    self.install_info, self.note) = _config_parsing.parse_version_ini(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/ungoogled-chromium-binaries/ungoogled-chromium-binaries/utilities/_config_parsing.py", line 23, in parse_version_ini
    publication_time = datetime.datetime.strptime(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/_strptime.py", line 554, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.2/x64/lib/python3.12/_strptime.py", line 336, in _strptime
    raise ValueError("unconverted data remains: %s" %
ValueError: unconverted data remains: +00:00
```

**Comment by Nifury** [comment]
Yeah but they are fixed in your PR https://github.com/ungoogled-software/ungoogled-chromium-binaries/pull/517.
I guess it would be easier to merge if I leave those files intact?

**Review by clickot — APPROVED** [review]

**Pull request merged**
