### PR TITLE
Add 79.0.3945.88-1 for macOS

### PR DESCRIPTION
**Pull request by kramred**

### CODE REVIEW

**Comment by Eloston** [comment]
Is the macOS PR for 79.0.3945.88 in the works?

**Comment by kramred** [comment]
Did not need any changes, build passed with repo at b3c75e415a6d61ea7de2f141760194293db3cf89

**Comment by Eloston** [comment]
But `b3c75e415a6d61ea7de2f141760194293db3cf89` is for version `.79-1.1`. Did you just update `chromium_version.txt` inside the ungoogled-chromium submodule?

**Comment by kramred** [comment]
Yes, sorry forgot to mention – I used https://github.com/Zoraver/ungoogled-chromium repo at the stage of the PR, will update macOS repo, add tag, and open PR for macOS repo

**Comment by kramred** [comment]
I've tried to create a PR for the macOS repo, but I don't really understand how the submodule reference works and if adding the tag `79.0.3945.88-1` worked. Please check the PR (the submodule looks ok to me) and add the tag if it's not included.

**Comment by Eloston** [comment]
Tags aren't included in PRs. I always add them in myself.

> I don't really understand how the submodule reference works

Submodules aren't anything too conceptually fancy. They're essentially a git repo inside a git repo, but the submodule's `.git` is stored inside the parent `.git`'s directory in a git clone. The parent git repo stores a reference to the remote, commit, and location within its repository. That's pretty much it. If you want more details, I think the git book on git's official website does a good job explaining it.

Going to merge this now. Thanks!

**Pull request merged**
