### PR TITLE
add 75.0.3770.90-1.1 macOS binary (as dev)

### PR DESCRIPTION
**Pull request by macvip**
add 75.0.3770.90-1.1 macOS binary as development

### CODE REVIEW

**Comment by IvanTrendafilov** [comment]
I wonder how you built this as 75.0.3770.90-1.1 contains a 404 error for google-toolbox-for-mac

**Comment by kramred** [comment]
@IvanTrendafilov – the 404 error is due to a missing character in the URL, you can fix it by prepending a "v" before "%(version)s.tar.gz". I also submitted a pull req. to fix it

**Comment by IvanTrendafilov** [comment]
I managed to build it ([see here for my change](https://github.com/ungoogled-software/ungoogled-chromium-macos/issues/14#issuecomment-503011415)), however I question the practice of publishing a binary (even a dev one) for a tag that obviously does not build

**Comment by macvip** [comment]
> I managed to build it ([see here for my change](https://github.com/ungoogled-software/ungoogled-chromium-macos/issues/14#issuecomment-503011415)), however I question the practice of publishing a binary (even a dev one) for a tag that obviously does not build without uncommitted edits to the build script config

Please have a look at this commit [from my previous fork](https://github.com/macvip/ungoogled-chromium-macos/commit/b1284f75b583d501477d2511ac1bb95e4cf4c744). The version is simply 2.2.1.
It was supposed to have a pull request however forgotten, while it was indeed mentioned in [this commit](https://github.com/ungoogled-software/ungoogled-chromium-binaries/pull/74).

**Comment by IvanTrendafilov** [comment]
Thanks-- don't get me wrong, I appreciate what this project is doing and I'm glad it exists. I do think it is important that the tags are buildable precisely because everyone is an anonymous / semi-anonymous volunteer and might publish a compromised binary. That's much harder to accomplish via source.

**Pull request merged**
