### PR TITLE
Add 80.0.3987.162-1.1 for Portable Linux 64-bit (musl)

### PR DESCRIPTION
**Pull request by Cubified**
Based on https://github.com/ungoogled-software/ungoogled-chromium-portablelinux/pull/42 (with some musl-specific changes)

### CODE REVIEW

**Comment by Eloston** [comment]
We should publish the source code for this binary somewhere before we merge. Do you think the musl-specific changes will be minimal? If so, we can create a new branch on ungoogled-chromium-portablelinux. Otherwise, we should create a new repo.

**Comment by Cubified** [comment]
Hi Eloston, good point -- my bad for jumping the gun like that.  I've published my changes to [Cubified/ungoogled-chromium-portablelinux-musl](https://github.com/Cubified/ungoogled-chromium-portablelinux-musl) -- altogether it's about [30 patches](https://github.com/Cubified/ungoogled-chromium-portablelinux-musl/commit/f2e6a3bda7769ba1c2b710b1e66d2ca470e7b5d6#diff-9d9aa5ea8f98bb87904331a122e98abc), most of which coming from the [Alpine Linux aports](https://git.alpinelinux.org/aports/tree/community/chromium) plus a few I've made.  I'm not certain I would call them minimal because of that, but it's entirely up to you.

Thanks,
Andrew

**Comment by Eloston** [comment]
In the long term, do you think the repo will diverge from ungoogled-chromium-portablelinux or continue to track its changes?

**Comment by Cubified** [comment]
It'll track its changes -- long term, only minor musl-specific patches should be necessary (hopefully).

**Comment by Eloston** [comment]
OK I merged your repo into a new branch `musl` and added a new directory in this repo for 64-bit musl builds. Also since you updated to 81, I'll just close this PR...

**Comment by Cubified** [comment]
Great, thanks so much -- I'll see what I can do about compiling a binary for 81.

**Pull request closed without merging**
