### PR TITLE
Add packages for 17.04

### PR DESCRIPTION
**Pull request by brokoli-mate**

### CODE REVIEW

**Comment by Eloston** [comment]
Thanks for contributing your time and computational resources to this project.

I saw you used the instructions I made in [this comment](https://github.com/Eloston/ungoogled-chromium/issues/218#issuecomment-297638398). Unfortunately, those instructions were not very precise. Please follow the [new instructions I just pushed](https://github.com/ungoogled-software/ungoogled-chromium-binaries#publishing-new-binaries).

For this particular situation, you'll also need to revert that commit somehow and create a new one in its place. I think it might be possible to delete the commit and force push a new one that will be reflected in this pull request, but I'm not certain.

Sorry for any confusion and inconveniences I've caused. Let me know if you have any questions.

**Comment by brokoli-mate** [comment]
Can you give me instructions how to use rhose *.py scripts? how to run, what commads should I use and so on.

**Comment by Eloston** [comment]
You mean `site_generator.py` and `platform_ini_generator.py`? As stated in those instructions, `site_generator.py` does not take arguments, and `platform_ini_generator.py` has usage information via `--help`.

I will clarify what directory to run these scripts in and improve `platform_ini_generator.py`'s usage information.

**Comment by brokoli-mate** [comment]
so i sould run them directly from browser? how can i do that. i'm totally new to this.

**Comment by Eloston** [comment]
@brokoli-mate You need to have Python 3 installed on your machine. Then you need to install Python-Markdown as it says in the requirements (via `pip`, since there is a PyPI link in the README). Then you can use the command-line to run the Python scripts. There are many examples on the web for learning to use Python from the command-line and using `pip`.

**Comment by Eloston** [comment]
If you want, I can update the binaries repository myself if you already have the binaries uploaded somewhere.

**Comment by brokoli-mate** [comment]
Sorry for doing nothing for so long time, it would be great if you update it yourself. https://github.com/brokoli-mate/ungoogled-chromium-binaries/tree/master/releases/ubuntu/17.04/chromium-browser_57.0.2987.133-1_amd64 here are they.

**Comment by Eloston** [comment]
It's harder to link to binaries in a git repository. Do you have them in a GitHub Release?

**Comment by brokoli-mate** [comment]
https://github.com/brokoli-mate/ungoogled-chromium-binaries/releases

**Comment by Eloston** [comment]
Finished in 40627213a21144c0c4f6a65ba04d8292e1c98792

**Pull request closed without merging**
