### PR TITLE
macOS 73.0.3683.103-1 and push 72.0.3626.122-4 to release

### PR DESCRIPTION
**Pull request by chase9**
- Fixed suffix for 72.0.3626.122-4 which would cause issues with homebrew

### CODE REVIEW

**Comment by chase9** [comment]
Recent binaries have started being output with the formatting of 72.0.3626.122-4*.1*_macos, and I'm not sure why. The revision number is still there, but the .1 is new to me. In my change I just took off the .1 from the previous binary I uploaded where I missed the .1.

The issue is that homebrew formulae don't expect this .1 to be there, and therefore aren't able to pull down new versions. We could change the brew but I'm not sure if this would affect our ability to download older versions via brew?

I guess the question is why is that .1 being appended onto the binary now?

**Comment by Eloston** [comment]
This is a new feature of the fragmentation refactor (https://github.com/Eloston/ungoogled-chromium/issues/651). As a result, macOS builds now need two repositories. The first number represents the revision of the main ungoogled-chromium repo, and the second represents the revision of the macOS repo (i.ie. `ungoogled-chromium-macos`).

If there's no way to make Homebrew handle both version schemes, I think it should be fine to hard-code it to new versions. I can't think of any reason off the top of my head why anyone would want to download an older version.

**Comment by chase9** [comment]
Sounds good. I had (wrongly) assumed this to be an artifact, but I see I should have asked first! I will fix right away and update the brew formula once this is merged to prevent disruption.

**Comment by chase9** [comment]
Question: should the tags for macOS now reflect the macOS revision number?

**Comment by chase9** [comment]
Also, I apologize but I was wrong about needing to change the brew formula. It feeding the new version scheme into it still works fine.

**Comment by Eloston** [comment]
> Question: should the tags for macOS now reflect the macOS revision number?

All the tags under `ungoogled-chromium-macos` have the new macOS revision number. Old versions should be left alone.

> Also, I apologize but I was wrong about needing to change the brew formula. It feeding the new version scheme into it still works fine.

:+1:

**Pull request merged**
